# Generated by Django 6.0.3 on 2026-03-25 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.TextField(unique=True)),
                ('specialty', models.TextField()),
                ('license_number', models.TextField(unique=True)),
                ('hospital', models.TextField()),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.TextField()),
                ('level', models.IntegerField()),
                ('score', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('accuracy', models.IntegerField(blank=True, null=True)),
                ('stars_caught', models.IntegerField(blank=True, null=True)),
                ('matches_made', models.IntegerField(blank=True, null=True)),
                ('objects_caught', models.IntegerField(blank=True, null=True)),
                ('shoulder_activation', models.IntegerField(blank=True, null=True)),
                ('elbow_activation', models.IntegerField(blank=True, null=True)),
                ('wrist_activation', models.IntegerField(blank=True, null=True)),
                ('grip_activation', models.IntegerField(blank=True, null=True)),
                ('external_rotation', models.IntegerField(blank=True, null=True)),
                ('shoulder_shrug', models.IntegerField(blank=True, null=True)),
                ('completed', models.IntegerField(blank=True, null=True)),
                ('session_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game_sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.TextField(unique=True)),
                ('date_of_birth', models.TextField()),
                ('gender', models.TextField()),
                ('medical_condition', models.TextField()),
                ('therapy_type', models.TextField()),
                ('current_level', models.IntegerField(blank=True, null=True)),
                ('assigned_doctor_id', models.IntegerField(blank=True, null=True)),
                ('emergency_contact_name', models.TextField(blank=True, null=True)),
                ('emergency_contact_phone', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('shoulder_strength', models.IntegerField(blank=True, null=True)),
                ('elbow_strength', models.IntegerField(blank=True, null=True)),
                ('grip_strength', models.IntegerField(blank=True, null=True)),
                ('affected_hand', models.TextField()),
                ('photo_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('role', models.TextField()),
                ('phone', models.TextField()),
                ('avatar', models.TextField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, default=1, null=True)),
                ('last_login', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('updated_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField()),
                ('sender_type', models.CharField(max_length=10)),
                ('receiver_id', models.IntegerField()),
                ('receiver_type', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
    ]
