# Generated by Django 6.0.3 on 2026-03-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'managed': False},
        ),
    ]
