# Generated by Django 4.2 on 2026-05-03 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_messages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('total_score', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('stars_collected', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.users')),
            ],
            options={
                'db_table': 'patient_progress',
            },
        ),
    ]
