# Generated by Django 4.2 on 2026-05-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patientprogress'),
    ]

    operations = [
    ]
