# Generated by Django 4.2 on 2026-05-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20260503_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_type', models.CharField(choices=[('stars', 'Catching Stars'), ('matching', 'Matching Game'), ('objects', 'Catching Objects')], max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('stars_earned', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'game_sessions',
                'ordering': ['-completed_at'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='GameSessions',
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'managed': False, 'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='patientprogress',
            options={'managed': False},
        ),
    ]
