# Generated by Django 5.2.12 on 2026-05-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_doctors_gamesessions_patients_delete_gamesession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesessions',
            options={'managed': True},
        ),
    ]
